"""rename department

Revision ID: 0a25e7f27130
Revises: dba5e92d0ee8
Create Date: 2024-10-13 20:41:06.490883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a25e7f27130'
down_revision = 'dba5e92d0ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', "department")
    # ### end Alembic commands ###
